# -*- coding: utf-8 -*-
"""1-Hafta-Odev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eC7RQz-jbFLYZt4qVLawOaAds5NqP4cX
"""

# Değişken Tipleri
user = "ali kemal kara"
userType = type(user)

age = 20
ageType = type(age)

balance = 500.0
balanceType = type(balance)

month = "april"
monthType = type(month)

isActive = True
isActiveType = type(isActive)

print(f"'{user}' değerinin tipi {userType}")
print(f"'{age}' değerinin tipi {ageType}")
print(f"'{balance}' değerinin tipi {balanceType}")
print(f"'{month}' değerinin tipi {monthType}")
print(f"'{isActive}' değerinin tipi {isActiveType}")

# Primitif değişkenler yok. Her şey obje :D
sayi = -10
print(sayi.__abs__())  # Çıktı: 10 (Mutlak değer metodu)

# abs(sayi) == sayi.__abs__()
print(abs(sayi) == sayi.__abs__())  # Çıktı: True (Mutlak değer metodu ile karşılaştırma

durum = True
print(durum.__int__())  # Çıktı: 1 (Tamsayıya çevirme metodu)

# List - Dict
harcamalar = []

harcamalar.append({"kategori": "yemek", "tutar": 150.0, "tarih": "2024-04-24"})
harcamalar.append({"kategori": "alisveris", "tutar": 250.0, "tarih": "2024-04-24"})
harcamalar.append({"kategori": "evcil hayvan", "tutar": 350.0, "tarih": "2024-04-25"})
harcamalar.append({"kategori": "diger", "tutar": 450.0, "tarih": "2024-04-25"})
harcamalar.append({"kategori": "eglence", "tutar": 550.0, "tarih": "2024-04-26"})
harcamalar.append({"kategori": "yemek", "tutar": 200.0, "tarih": "2024-04-27"})
harcamalar.append({"kategori": "alisveris", "tutar": 300.0, "tarih": "2024-04-27"})
harcamalar.append({"kategori": "evcil hayvan", "tutar": 400.0, "tarih": "2024-04-28"})
harcamalar.append({"kategori": "alisveris", "tutar": 500.0, "tarih": "2024-04-28"})

print(harcamalar)
print("---------------------------")


print("Harcama Adedi ", len(harcamalar))
print("---------------------------")

toplam_harcama = sum(i["tutar"] for i in harcamalar)
print(f"Toplam yapılan harcama : {toplam_harcama}")
print("---------------------------")

print(harcamalar[1]["kategori"])

harcamalar[1].update({"kategori": "yemek"}) # harcamalar[1]["kategori"] = "yemek"

print(harcamalar[1]["kategori"])
print("---------------------------")

print(harcamalar[0].items())
print(harcamalar[0].keys())
print(harcamalar[0].values())
print("---------------------------")

