# -*- coding: utf-8 -*-
"""2-Hafta-Odev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eC7RQz-jbFLYZt4qVLawOaAds5NqP4cX
"""

# List - Dict
harcamalar = []

harcamalar.append({"kategori": "yemek", "tutar": 150.0, "tarih": "2024-04-24"})
harcamalar.append({"kategori": "alisveris", "tutar": 250.0, "tarih": "2024-04-24"})
harcamalar.append({"kategori": "evcil hayvan", "tutar": 350.0, "tarih": "2024-04-25"})
harcamalar.append({"kategori": "diger", "tutar": 450.0, "tarih": "2024-04-25"})
harcamalar.append({"kategori": "eglence", "tutar": 550.0, "tarih": "2024-04-26"})
harcamalar.append({"kategori": "yemek", "tutar": 200.0, "tarih": "2024-04-27"})
harcamalar.append({"kategori": "alisveris", "tutar": 300.0, "tarih": "2024-04-27"})
harcamalar.append({"kategori": "evcil hayvan", "tutar": 400.0, "tarih": "2024-04-28"})
harcamalar.append({"kategori": "alisveris", "tutar": 500.0, "tarih": "2024-04-28"})

def harcamaEkle(kategori, tutar, tarih):
    harcamalar.append({"kategori": kategori, "tutar": tutar, "tarih": tarih})

def harcamalariListele():
    for harcama in harcamalar:
        print(f"Kategori: {harcama['kategori']}, Tutar: {harcama['tutar']}, Tarih: {harcama['tarih']}")

harcamalariListele()
print("----------------------")

def harcamaFiltrele(kategori):
    sonuclar = [h for h in harcamalar if h["kategori"] == kategori]
    return sonuclar


print(f"diger kategorisinde yapılan harcamalar:  {harcamaFiltrele("diger")}")
print("----------------------")

def kategoriHarcamaTopla(kategori):
    toplam = 0
    for harcama in harcamalar:
        if harcama["kategori"] == kategori:
            toplam += harcama["tutar"]
    return toplam

print(f"yemek kategorisindeki toplam: {kategoriHarcamaTopla('yemek')}")

print("----------------------")
def harcamaTopla():
    toplam = 0
    for harcama in harcamalar:
        toplam += harcama["tutar"]
    return toplam

print(f"yapılan toplam harcama miktarı {harcamaTopla()}")
print("----------------------")
def kullanicidanHarcamaEkle():
    kategori = input("Kategori girin: ")
    tarih = input("Tarih girin (YYYY-MM-DD): ")
    try:
        tutar = float(input("Tutar girin: "))
        harcamaEkle(kategori, tutar, tarih)
        print("Harcama başarıyla eklendi.")
    except ValueError:
        print("Hata: Tutar sayısal bir değer olmalı. Harcama eklenmedi.")

# kullanicidanHarcamaEkle()

print("---------------")

def kullanicidanFiltrele():
    kategori = input("Hangi kategoriyi aramak istersiniz? ")
    sonuclar = harcamaFiltrele(kategori)
    if not sonuclar:
        print(f"'{kategori}' kategorisinde herhangi bir harcama bulunamadı.")
    else:
        print(f"{kategori} kategorisinde yapılan harcamalar:")
        for h in sonuclar:
            print(f"  {h}")

# kullanicidanFiltrele()
print("-------------")